### ISSUE TITLE
What about goose-starter-kit

### ISSUE THREAD

**Issue by jifeon** [redco/goose-parser#22]
A project with configured build for browser env and working basic usage example. Users will be able to clone this repo and start hacking!

**Comment by maZahaca** [comment]
Great suggestion!

**Comment by maZahaca** [comment]
But is that the same as done in the tests for BrowserEnvironment?

**Comment by jifeon** [comment]
Imagine that you are goose user, you install goose-parser through npm, and you even do not have folder with tests.. wtf?

If we have starter-kit, everything will be clear and useful. Trust me :boar:

**Comment by maZahaca** [comment]
example https://github.com/kriasoft/react-starter-kit

**Comment by maZahaca** [comment]
repo https://github.com/redco/goose-starter-kit
