### ISSUE TITLE
Ability to use in one scope results of another one located on the same level

### ISSUE THREAD

**Issue by maZahaca** [redco/goose-parser#60]
For example we need to do two actions:
- parse URL
- parse Id from URL (to simplify that action we should use results from first one).

**Comment by jifeon** [comment]
yep, it would be great to have access to already built results tree

**Comment by maZahaca** [comment]
That is done through the storage. You could set and get data in it.

**Comment by maZahaca** [comment]
Rules example:
```js
{
        scope: '.data',
        collection: [[
            {
                "name": "url",
                "attr": "href",
                "set": "url"
            },
            {
                "id": true,
                "get": "url"
            }
        ]]
    }
```

So, url from "href" was parsed only once, and then reused in the second row
