### ISSUE TITLE
Update tests according to the changes in 0.5.0 and add circle-ci

### ISSUE THREAD

**Issue by maZahaca** [redco/goose-parser#77]
Move current test system to new efficient way (Take a look on new tests here https://github.com/redco/goose-parser/pull/76)

So, we have:
old tests here: `tests/phantom_parser_test.js`
new tests here: `tests/phantom/lib/`

To run tests, just call `npm test`

When move some test, remove it in `tests/phantom_parser_test.js`
At the end remove a file tests/phantom_parser_test.js and html page for it.

**Comment by maZahaca** [comment]
@1gory take a look on this. I would be appreciate for doing this ticket.

**Comment by jifeon** [comment]
@1gory Feel free to ping me in skype for clarifications. It's not necessary to move all the tests in one commit/PR. Let's start with first one from `tests/phantom_parser_test.js`.

**Comment by maZahaca** [comment]
A branch to start from is [feature-goose-babe](https://github.com/redco/goose-parser/tree/feature-goose-babe)
